version: "3.9"

services:
  db:
    image: postgres:16
    container_name: atividade04-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livrosdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: atividade04-backend
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=livrosdb
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    command: npm start

  frontend:
    build: ./frontend
    container_name: atividade04-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
